  FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
  RUN apt-get update && apt-get install -y libgdiplus
  EXPOSE 8080
  EXPOSE 443
  COPY bin/Release/net8.0/publish/ app/
  WORKDIR /app
  
  FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
  WORKDIR /src
  #RUN dotnet dev-certs https -v -ep openiddict.pfx -p 624d896a-eeb7-4769-ac0c-9a19a85db3cc
  
  FROM base AS final
  WORKDIR /app
  COPY --from=build /src .
    
  ENTRYPOINT ["dotnet", "Acme.BookStore.Report.Blazor.dll"]